server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://172.16.22.47:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 139.224.200.249:2181
      namespace: pig-daemon
